---
title: "Tech Financials"
author: "Richard Tarbell"
date: "8/31/2021"
output: 
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(psych)
library(here)
# OPTION + CTRL + i
```

##Reading data

We have a stata file so we use 'haven' package to read it
```{r}
d1 <- haven::read_dta("tech_co_cstat_dta.zip")
```



```{r}
class(d1)
```

```{r}
names(d1)
```


```{r}
head(d1, n=10)
```


```{r}
tail(d1, n=3)
```


```{r}
d1[1:10,]
```


```{r}
attributes(d1$gvkey)
```

```{r}
attributes(d1$datadate)
```

```{r}
attributes(d1$datadate)$label <- "Fiscal year end date"
```

```{r}
attributes(d1$datadate)
```


```{r}
glimpse(d1)
```

```{r} 
# use desribe instead of summary for different sets of data
psych::describe(d1)
```


```{r}
table(d1$gvkey)
```


```{r}
table(d1$conm)
```

```{r}
count(d1, conm)
```

### Select()

```{r}
d2 <- select(d1, conm, datadate, sale, xrd)
```


```{r}
d2 <- select(d1, -gvkey)
```


```{r}
d3 <- d1 %>%
  select(-gvkey) %>%
  head()
```

```{r}
d4 <- head(select(d1, -gvkey))
```

```{r}
identical(d3,d4)
```

```{r}
a <- 50

if (a >= 50) {
  print("the number is greater than or equal to 50")
  } else(print("the number is smaller than 50"))
```

### Filter() 

```{r}
mean(d1$sale, na.rm = TRUE)
```


```{r}
d5 <- d1 %>%
  filter(sale > 0)
```

```{r}
mean(d5$sale)
```


```{r}
d1$sale %>%
  is.na()
```

```{r}
d6 <- d1 %>%
  filter(!is.na(sale))
```




Output the missing value status

```{r echo = TRUE, eval=FALSE}
!is.na(d1$sale)

```


```{r}
head(d1$sale)
```

### Mutate()
ALlows us to create new variables

```{r}
d7 <- d5 %>%
  mutate(profit_margin = oibdp / sale,
         cash_holding = che / at,
         rnd_intensity = xrd / sale,
         debt_lt = ifelse(is.na(dltt), 0, dltt)) # if dltt is NA set it to 0. if not keep it as dltt
      
```

```{r}
head(d5$dltt)
```

```{r}
is.na(d5$dltt) %>% sum()
```


```{r}
d8 <- d7 %>%
  arrange(conm, datadate) %>% # order the df by company name and dates
  group_by(conm) %>% # group by company name so the lag function doesn't go to a previous company
  mutate(sales_gr = (sale - lag(sale)) / lag(sale)) # sales growth
```


```{r}
d8 %>%
  select(conm, datadate, sale, sales_gr) %>%
  head(20)
```



```{r}
d7 %>%
  select(sale) %>%
  summarize(sale_mean = mean(sale),
            sale_median = median(sale),
            sale_sd = sd(sale))
```



```{r}
d7 %>%
  select(sale, at, xrd) %>%
  summarize(across(everything(), mean))
```


```{r}
d7 %>%
  group_by(conm) %>%
  summarize(sale_mean = mean(sale),
            sale_median = median(sale),
            sale_sd = sd(sale)) %>%
  as.data.frame() # This will show the decimal places in the knitted file. Use for HW1.
```











